### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by Blakechez** [eatmyvenom/litematica-printer#12]
the read me doesn't say what to do, do I run the batch file? do i put the jar file in my mods folder? is there some other program i need to run one of the files to set it up? after I ran the batch file and nothing happened when I went in to Minecraft and turned on easyplace I tried executing also and that did nothing, please help

**Comment by Vaneklegio** [comment]
The first line of the instructions: 
"To set this up just add the latest litematica version to your mods folder as well as this."
All you need to do is downolad the jar and add it to your mods folder.

**Comment by Blakechez** [comment]
which one theres like 20

**Comment by Vaneklegio** [comment]
From the "release 1.0.0" page, download "litematica-printer-mc1.16.2-1.0.0.jar".
Then move it to your mods folder (I assume you know where that is, since you already have litematica instaled).
That's it. no need to extract anything, or run anything. The next time you launch Minecraft, the mod will be active.
